long_name = "Auto Use Tweaks"
short_name = "auto_use_tweaks"
for_module = "tome"
version = {1,7,6}
addon_version = {0,0,1}
weight = 100
author = { "Gleesus", "admin@gleesus.net" }
homepage = "http://tome.te4.org/"
description = [[Auto use 3: Auto usealoo]]
tags = {'auto-use', 'tweaks', 'auto', 'talent', 'use', 'custom'}
overload = true
superload = true
hooks = true
data = true
